name: tao996
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.11.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.16.0
  collection: ^1.19.1
  crypto: ^3.0.7
  path: ^1.9.1
  intl: ^0.20.2
  mime: ^2.0.0
  fast_gbk: ^1.0.0
  permission_handler: ^12.0.3
  url_launcher: ^6.3.2
  flutter_svg: ^2.3.0
  qr_flutter: ^4.1.0
  sqflite: ^2.4.2+1
  device_info_plus: ^13.1.0
  dio: ^5.9.2
  connectivity_plus: ^7.1.1
  fluttertoast: ^9.1.0
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

